third_party\upb\upb/message/internal/accessors.h(186): warning C4098: '_upb_MiniTableField_DataClear_dont_copy_me__upb_internal_use_only': 'void' function
 returning a value
      third_party\upb\upb/message/accessors.h(414): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      C:\Users\julio\AppData\Local\Temp\pip-install-gnwj9vuj\grpcio_f6af1a3b150b4a289d0067cdee028369\src\core\ext\upb-gen\envoy\extensions\load_balancing_polici
es\client_side_weighted_round_robin\v3\client_side_weighted_round_robin.upb_minitable.c : fatal error C1083: Cannot open compiler generated file: '': Invalid ar
gument
      creating Users\julio\AppData\Local\Temp\tmp4bowxgiu
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\Docume
ntos\DevProjects\GCP-etl-r32-wt\dev\.venv\include -IC:\Python313\include -IC:\Python313\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\To
ols\MSVC\14.44.35207\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\incl
ude\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\sha
red" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /TcC:\Us
ers\julio\AppData\Local\Temp\tmp4bowxgiu\a.c /FoUsers\julio\AppData\Local\Temp\tmp4bowxgiu\a.obj
      a.c
      Traceback (most recent call last):
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 87, in spawn
          subprocess.check_call(cmd, env=_inject_macos_ver(env))
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python313\Lib\subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64\\cl
.exe', '/c', '/nologo', '/O2', '/W3', '/GL', '/DNDEBUG', '/MD', '-D_WIN32_WINNT=1536', '-DGRPC_XDS_USER_AGENT_NAME_SUFFIX="\\"Python\\""', '-DGRPC_XDS_USER_AGEN
T_VERSION_SUFFIX="\\"1.66.1\\""', '-DOPENSSL_NO_ASM=1', '-DWIN32_LEAN_AND_MEAN=1', '-DCARES_STATICLIB=1', '-DGRPC_ARES=0', '-DNTDDI_VERSION=100663296', '-DNOMIN
MAX=1', '-DMS_WIN64=1', '-DGRPC_DO_NOT_INSTANTIATE_POSIX_POLLER=1', '-D__STDC_FORMAT_MACROS', '-Isrc\\python\\grpcio', '-Iinclude', '-I.', '-Ithird_party\\absei
l-cpp', '-Ithird_party\\address_sorting\\include', '-Ithird_party\\cares\\cares\\include', '-Ithird_party\\cares', '-Ithird_party\\cares\\cares', '-Ithird_party
\\re2', '-Ithird_party\\boringssl-with-bazel\\src\\include', '-Ithird_party\\upb', '-Isrc\\core\\ext\\upb-gen', '-Isrc\\core\\ext\\upbdefs-gen', '-Ithird_party\
\utf8_range', '-Ithird_party\\xxhash', '-Ithird_party\\zlib', '-ID:\\Documentos\\DevProjects\\GCP-etl-r32-wt\\dev\\.venv\\include', '-IC:\\Python313\\include', 
'-IC:\\Python313\\Include', '-IC:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\include', '-IC:\\Program Files\\Micros
oft Visual Studio\\2022\\Community\\VC\\Auxiliary\\VS\\include', '-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt', '-IC:\\Program File
s (x86)\\Windows Kits\\10\\\\include\\10.0.19041.0\\\\um', '-IC:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.19041.0\\\\shared', '-IC:\\Program File
s (x86)\\Windows Kits\\10\\\\include\\10.0.19041.0\\\\winrt', '-IC:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.19041.0\\\\cppwinrt', '/EHsc', '/Tcs
rc/core/ext/upb-gen/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/client_side_weighted_round_robin.upb_minitable.c', '/Fopyb\\tem
p.win-amd64-cpython-313\\Release\\src\\core\\ext\\upb-gen\\envoy\\extensions\\load_balancing_policies\\client_side_weighted_round_robin\\v3\\client_side_weighte
d_round_robin.upb_minitable.obj', '/std:c11', '/MT']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\msvc.py", line 460, in compil
e
          self.spawn(args)
          ~~~~~~~~~~^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\msvc.py", line 563, in spawn 
          return super().spawn(cmd, env=env)
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-install-gnwj9vuj\grpcio_f6af1a3b150b4a289d0067cdee028369\src\python\grpcio\_spawn_patch.py", line 58, in _co
mmandfile_spawn
          _classic_spawn(self, command, **kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\base.py", line 1158, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
          ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 93, in spawn
          raise DistutilsExecError(
              f"command {_debug(cmd)!r} failed with exit code {err.returncode}"
          ) from err
      distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64
\\cl.exe' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\julio\AppData\Local\Temp\pip-install-gnwj9vuj\grpcio_f6af1a3b150b4a289d0067cdee028369\src\python\grpcio\commands.py", line 313, in build_
extensions
          build_ext.build_ext.build_extensions(self)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 484, in build
_extensions
          self._build_extensions_serial()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 510, in _buil
d_extensions_serial
          self.build_extension(ext)
          ~~~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 261, in build_extension 
          _build_ext.build_extension(self, ext)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 565, in build
_extension
          objects = self.compiler.compile(
              sources,
          ...<5 lines>...
              depends=ext.depends,
          )
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\msvc.py", line 462, in compil
e
          raise CompileError(msg)
      distutils.compilers.C.errors.CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX8
6\\x64\\cl.exe' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "D:\Documentos\DevProjects\GCP-etl-r32-wt\dev\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module
>
          main()
          ~~~~^^
        File "D:\Documentos\DevProjects\GCP-etl-r32-wt\dev\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main   
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Documentos\DevProjects\GCP-etl-r32-wt\dev\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_w
heel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              metadata_directory)
                                              ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\build_meta.py", line 435, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\build_meta.py", line 423, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\build_meta.py", line 512, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 579, in <module>
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\__init__.py", line 115, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 186, in setup
          return run_commands(dist)
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 202, in run_commands      
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 1002, in run_commands     
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\dist.py", line 1102, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 1021, in run_command      
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py", line 370, in run
          self.run_command("build")
          ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 357, in run_command        
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\dist.py", line 1102, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 1021, in run_command      
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run      
          self.run_command(cmd_name)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 357, in run_command        
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\dist.py", line 1102, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 1021, in run_command      
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 96, in run
          _build_ext.run(self)
          ~~~~~~~~~~~~~~^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 368, in run  
          self.build_extensions()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\julio\AppData\Local\Temp\pip-install-gnwj9vuj\grpcio_f6af1a3b150b4a289d0067cdee028369\src\python\grpcio\commands.py", line 317, in build_
extensions
          raise CommandError(
              "Failed `build_ext` step:\n{}".format(formatted_exception)
          )
      commands.CommandError: Failed `build_ext` step:
      Traceback (most recent call last):
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 87, in spawn
          subprocess.check_call(cmd, env=_inject_macos_ver(env))
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python313\Lib\subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64\\cl
.exe', '/c', '/nologo', '/O2', '/W3', '/GL', '/DNDEBUG', '/MD', '-D_WIN32_WINNT=1536', '-DGRPC_XDS_USER_AGENT_NAME_SUFFIX="\\"Python\\""', '-DGRPC_XDS_USER_AGEN
T_VERSION_SUFFIX="\\"1.66.1\\""', '-DOPENSSL_NO_ASM=1', '-DWIN32_LEAN_AND_MEAN=1', '-DCARES_STATICLIB=1', '-DGRPC_ARES=0', '-DNTDDI_VERSION=100663296', '-DNOMIN
MAX=1', '-DMS_WIN64=1', '-DGRPC_DO_NOT_INSTANTIATE_POSIX_POLLER=1', '-D__STDC_FORMAT_MACROS', '-Isrc\\python\\grpcio', '-Iinclude', '-I.', '-Ithird_party\\absei
l-cpp', '-Ithird_party\\address_sorting\\include', '-Ithird_party\\cares\\cares\\include', '-Ithird_party\\cares', '-Ithird_party\\cares\\cares', '-Ithird_party
\\re2', '-Ithird_party\\boringssl-with-bazel\\src\\include', '-Ithird_party\\upb', '-Isrc\\core\\ext\\upb-gen', '-Isrc\\core\\ext\\upbdefs-gen', '-Ithird_party\
\utf8_range', '-Ithird_party\\xxhash', '-Ithird_party\\zlib', '-ID:\\Documentos\\DevProjects\\GCP-etl-r32-wt\\dev\\.venv\\include', '-IC:\\Python313\\include', 
'-IC:\\Python313\\Include', '-IC:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\include', '-IC:\\Program Files\\Micros
oft Visual Studio\\2022\\Community\\VC\\Auxiliary\\VS\\include', '-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt', '-IC:\\Program File
s (x86)\\Windows Kits\\10\\\\include\\10.0.19041.0\\\\um', '-IC:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.19041.0\\\\shared', '-IC:\\Program File
s (x86)\\Windows Kits\\10\\\\include\\10.0.19041.0\\\\winrt', '-IC:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.19041.0\\\\cppwinrt', '/EHsc', '/Tcs
rc/core/ext/upb-gen/envoy/extensions/load_balancing_policies/client_side_weighted_round_robin/v3/client_side_weighted_round_robin.upb_minitable.c', '/Fopyb\\tem
p.win-amd64-cpython-313\\Release\\src\\core\\ext\\upb-gen\\envoy\\extensions\\load_balancing_policies\\client_side_weighted_round_robin\\v3\\client_side_weighte
d_round_robin.upb_minitable.obj', '/std:c11', '/MT']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\msvc.py", line 460, in compil
e
          self.spawn(args)
          ~~~~~~~~~~^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\msvc.py", line 563, in spawn 
          return super().spawn(cmd, env=env)
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-install-gnwj9vuj\grpcio_f6af1a3b150b4a289d0067cdee028369\src\python\grpcio\_spawn_patch.py", line 58, in _co
mmandfile_spawn
          _classic_spawn(self, command, **kwargs)
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\base.py", line 1158, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
          ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\spawn.py", line 93, in spawn
          raise DistutilsExecError(
              f"command {_debug(cmd)!r} failed with exit code {err.returncode}"
          ) from err
      distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX86\\x64
\\cl.exe' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\julio\AppData\Local\Temp\pip-install-gnwj9vuj\grpcio_f6af1a3b150b4a289d0067cdee028369\src\python\grpcio\commands.py", line 313, in build_
extensions
          build_ext.build_ext.build_extensions(self)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 484, in build
_extensions
          self._build_extensions_serial()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 510, in _buil
d_extensions_serial
          self.build_extension(ext)
          ~~~~~~~~~~~~~~~~~~~~^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 261, in build_extension 
          _build_ext.build_extension(self, ext)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 565, in build
_extension
          objects = self.compiler.compile(
              sources,
          ...<5 lines>...
              depends=ext.depends,
          )
        File "C:\Users\julio\AppData\Local\Temp\pip-build-env-cp0jl_k9\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\msvc.py", line 462, in compil
e
          raise CompileError(msg)
      distutils.compilers.C.errors.CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX8
6\\x64\\cl.exe' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
  Building wheel for MarkupSafe (pyproject.toml) ... done
  Created wheel for MarkupSafe: filename=markupsafe-2.1.5-cp313-cp313-win_amd64.whl size=17243 sha256=2cbebf2db8fa8ea83569d4186c8c7a05962d948674cebf67e93e013494
445c53
  Stored in directory: c:\users\julio\appdata\local\pip\cache\wheels\c2\0c\c0\d6d953ac80cacc2dd1d329d675c67d1e7775bad02a8faedef0
Successfully built google-crc32c MarkupSafe
Failed to build grpcio

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (grpcio)